CREATE TABLE blocks (
    id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    content_id INT(11) NOT NULL,
    type ENUM(
        'text',
        'image_text',
        'image',
        'cta',
        'post_picker',
        'video',
        'slider_gallery',
        'quote',
        'accordion',
        'audio',
        'free_code',
        'map',
        'form',
        'hero'
    ) NOT NULL,
    title VARCHAR(255),
    content MEDIUMTEXT,
    selected_post_ids TEXT,
    image_path VARCHAR(255),
    alt_text VARCHAR(255),
    caption VARCHAR(255),
    url1 VARCHAR(255),
    cta_text1 VARCHAR(255),
    url2 VARCHAR(255),
    cta_text2 VARCHAR(255),
    video_url VARCHAR(255),
    video_source ENUM('url', 'upload') DEFAULT 'url',
    video_file VARCHAR(255),
    audio_url VARCHAR(255),
    audio_source ENUM('url', 'upload') DEFAULT 'url',
    audio_file VARCHAR(255),
    slider_type ENUM('image', 'quote'),
    slider_speed INT(11),
    free_code_content MEDIUMTEXT,
    map_embed_code TEXT,
    form_shortcode TEXT,
    gallery_data MEDIUMTEXT,
    quotes_data MEDIUMTEXT,
    accordion_data MEDIUMTEXT,
    transition_speed INT,
    transition_effect ENUM('slide', 'fade'),
    autoplay BOOLEAN,
    pause_on_hover BOOLEAN,
    infinite_loop BOOLEAN,
    show_arrows BOOLEAN,
    show_dots BOOLEAN,
    dot_style ENUM('classic', 'thumbnail'),
    lazy_load BOOLEAN,
    aspect_ratio ENUM('16:9', '4:3', '1:1', 'custom'),
    lightbox_enabled BOOLEAN,
    thumbnail_path VARCHAR(255),
    background_type_desktop ENUM('image', 'video', 'color') DEFAULT 'image',
    background_type_tablet ENUM('image', 'video', 'color') DEFAULT 'image',
    background_type_mobile ENUM('image', 'video', 'color') DEFAULT 'image',
    background_image_desktop VARCHAR(255),
    background_image_tablet VARCHAR(255),
    background_image_mobile VARCHAR(255),
    background_video_url VARCHAR(255),
    background_color VARCHAR(255),
    background_opacity_desktop DECIMAL(3, 2),
    background_opacity_tablet DECIMAL(3, 2),
    background_opacity_mobile DECIMAL(3, 2),
    background_style ENUM('cover', 'contain', 'repeat', 'no-repeat') DEFAULT 'cover',
    hero_layout ENUM('left', 'center', 'right') DEFAULT 'center',
    overlay_color VARCHAR(255),
    text_color VARCHAR(255),
    text_size_desktop VARCHAR(255),
    text_size_tablet VARCHAR(255),
    text_size_mobile VARCHAR(255),
    padding_top_desktop VARCHAR(255),
    padding_right_desktop VARCHAR(255),
    padding_bottom_desktop VARCHAR(255),
    padding_left_desktop VARCHAR(255),
    padding_top_tablet VARCHAR(255),
    padding_right_tablet VARCHAR(255),
    padding_bottom_tablet VARCHAR(255),
    padding_left_tablet VARCHAR(255),
    padding_top_mobile VARCHAR(255),
    padding_right_mobile VARCHAR(255),
    padding_bottom_mobile VARCHAR(255),
    padding_left_mobile VARCHAR(255),
    margin_top_desktop VARCHAR(255),
    margin_right_desktop VARCHAR(255),
    margin_bottom_desktop VARCHAR(255),
    margin_left_desktop VARCHAR(255),
    margin_top_tablet VARCHAR(255),
    margin_right_tablet VARCHAR(255),
    margin_bottom_tablet VARCHAR(255),
    margin_left_tablet VARCHAR(255),
    margin_top_mobile VARCHAR(255),
    margin_right_mobile VARCHAR(255),
    margin_bottom_mobile VARCHAR(255),
    margin_left_mobile VARCHAR(255),
    layout1 VARCHAR(255),
    layout2 VARCHAR(255),
    layout3 VARCHAR(255),
    layout4 VARCHAR(255),
    layout5 VARCHAR(255),
    layout6 VARCHAR(255),
    layout7 VARCHAR(255),
    layout8 VARCHAR(255),
    layout9 VARCHAR(255),
    layout10 VARCHAR(255),
    style1 VARCHAR(255),
    style2 VARCHAR(255),
    style3 VARCHAR(255),
    style4 VARCHAR(255),
    style5 VARCHAR(255),
    style6 VARCHAR(255),
    style7 VARCHAR(255),
    style8 VARCHAR(255),
    style9 VARCHAR(255),
    style10 VARCHAR(255),
    responsive_class VARCHAR(255),
    responsive_style VARCHAR(255),
    border_style VARCHAR(255),
    border_color VARCHAR(255),
    border_width VARCHAR(255),
    animation_type VARCHAR(255),
    animation_duration VARCHAR(255),
    custom_css TEXT,
    custom_js TEXT,
    aria_label VARCHAR(255),
    text_size VARCHAR(255),
    class VARCHAR(255),
    metafield1 TEXT,
    metafield2 TEXT,
    metafield3 TEXT,
    metafield4 TEXT,
    metafield5 TEXT,
    metafield6 TEXT,
    metafield7 TEXT,
    metafield8 TEXT,
    metafield9 TEXT,
    metafield10 TEXT,
    order_num INT(11) NOT NULL,
    status ENUM('active', 'inactive') NOT NULL DEFAULT 'active',
    start_date DATETIME,
    end_date DATETIME,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (content_id) REFERENCES contents(id)
);